apiVersion: v1
kind: Service
metadata:
  name: inventory-manager
  labels:
    app: inventory-manager
spec:
  type: ClusterIP
  selector:
    app: inventory-manager
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
